services:
  chall:
      build: ./
      ports:
        - "9929:9929" # for challenge
        - "929:929" # for remote debugging
      cap_add:
        - SYS_PTRACE
      security_opt:
        - seccomp:unconfined
